apiVersion: v1
kind: PersistentVolume
metadata:
  name: langfuse-ch-iscsi
  labels:
    app: langfuse-clickhouse
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  iscsi:
    targetPortal: "192.168.30.205:3260"
    iqn: "iqn.2026-03.farm.haist:okd-langfuse-ch"
    lun: 0
    fsType: "xfs"
    readOnly: false
