apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: langfuse-clickhouse-data
  namespace: langfuse
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: langfuse-ch-iscsi
  resources:
    requests:
      storage: 100Gi
