apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: langfuse-s3-data
  namespace: langfuse
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-storage
  resources:
    requests:
      storage: 100Gi
