apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: falcosidekick-wazuh-indexer
  namespace: falco-system
  labels:
    app.kubernetes.io/name: falcosidekick
    app.kubernetes.io/component: event-forwarder
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: falcosidekick-wazuh-indexer
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: wazuh/indexer
        property: username
    - secretKey: password
      remoteRef:
        key: wazuh/indexer
        property: password
