apiVersion: v1
kind: Service
metadata:
  name: falcosidekick
  namespace: falco-system
  labels:
    app.kubernetes.io/name: falcosidekick
    app.kubernetes.io/component: event-forwarder
spec:
  selector:
    app.kubernetes.io/name: falcosidekick
  ports:
    - name: http
      port: 2801
      targetPort: 2801
      protocol: TCP
  type: ClusterIP
