apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - alloy-serviceaccount.yaml
  - alloy-scc.yaml
  - alloy-clusterrole.yaml
  - alloy-clusterrolebinding.yaml
  - alloy-configmap.yaml
  - alloy-daemonset.yaml
  - alloy-network-policy.yaml
