apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: netbox-postgresql-data
  namespace: netbox
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: netbox-pg-iscsi
  resources:
    requests:
      storage: 15Gi
