apiVersion: v1
kind: PersistentVolume
metadata:
  name: netbox-pg-iscsi
  labels:
    app: netbox-postgresql
spec:
  capacity:
    storage: 15Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: netbox-postgresql-data
    namespace: netbox
  iscsi:
    targetPortal: "192.168.30.205:3260"
    iqn: "iqn.2026-03.farm.haist:okd-netbox-pg"
    lun: 0
    fsType: "xfs"
    readOnly: false
