apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: harbor-postgresql-data
  namespace: harbor
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: harbor-pg-iscsi
  resources:
    requests:
      storage: 15Gi
