apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: alloy
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: https://forgejo.208.haist.farm/sentinel-admin/overwatch-gitops
    targetRevision: main
    path: apps/alloy
  destination:
    server: https://kubernetes.default.svc
    namespace: logging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
