apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: arch-vault-reader
  namespace: openshift-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://forgejo.208.haist.farm/sentinel-admin/overwatch-gitops
    targetRevision: main
    path: apps/arch-vault-reader
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-gitops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
