apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: machineconfigs
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: https://forgejo.208.haist.farm/sentinel-admin/overwatch-gitops.git
    targetRevision: main
    path: clusters/overwatch/machineconfigs
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-machine-config-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - ServerSideApply=true
