apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tiny-shortener
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: https://forgejo.208.haist.farm/sentinel-admin/overwatch-gitops.git
    targetRevision: main
    path: apps/tiny-shortener
  destination:
    server: https://kubernetes.default.svc
    namespace: tiny-shortener
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
