apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: matrix-postgresql-data
  namespace: matrix
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: matrix-pg-iscsi
  resources:
    requests:
      storage: 15Gi
