---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backstage-postgresql-data
  namespace: backstage
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: backstage-pg-iscsi
  resources:
    requests:
      storage: 10Gi
